import { ClaudeStructure, ClaudeProjectContext, ClaudeTeamContext, ClaudeBusinessContext } from '../types/claude-structure';
import { generateClaudeMd } from './claude-md';
import { generateSkills } from './skills';
import { generateHooks } from './hooks';
import { generateDocs } from './docs';

export interface GeneratedFile {
  path: string;
  content: string;
  description: string;
}

export interface ClaudePackage {
  structure: ClaudeStructure;
  files: GeneratedFile[];
  summary: ClaudePackageSummary;
}

export interface ClaudePackageSummary {
  totalFiles: number;
  skillsCount: number;
  hooksCount: number;
  docsCount: number;
  estimatedTimeSavings: string;
  keyBenefits: string[];
}

export function generateClaudeStructure(
  context: ClaudeProjectContext,
  teamContext: ClaudeTeamContext = {},
  businessContext: ClaudeBusinessContext = {}
): ClaudePackage {
  // Generate all components
  const claudeMd = generateClaudeMd(context, teamContext, businessContext);
  const skills = generateSkills(context);
  const hooks = generateHooks(context);
  const docs = generateDocs(context, teamContext, businessContext);

  const structure: ClaudeStructure = { claudeMd, skills, hooks, docs };

  // Build flat file list with paths
  const files: GeneratedFile[] = [
    {
      path: '.claude/CLAUDE.md',
      content: claudeMd,
      description: 'Project brain — context, conventions and rules for Claude Code',
    },
    ...skills.map((s) => ({
      path: `.claude/skills/${s.filename}`,
      content: s.content,
      description: s.description,
    })),
    ...hooks.map((h) => ({
      path: `.claude/hooks/${h.filename}`,
      content: h.content,
      description: h.description,
    })),
    ...docs.map((d) => ({
      path: `.claude/docs/${d.filename}`,
      content: d.content,
      description: d.description,
    })),
  ];

  const summary: ClaudePackageSummary = buildSummary(context, skills.length, hooks.length, docs.length);

  return { structure, files, summary };
}

function buildSummary(
  context: ClaudeProjectContext,
  skillsCount: number,
  hooksCount: number,
  docsCount: number
): ClaudePackageSummary {
  const totalFiles = 1 + skillsCount + hooksCount + docsCount; // 1 for CLAUDE.md

  // Estimate time savings based on team context and structure quality
  const baseSavingsPerMonth =
    skillsCount * 2 + // Each skill saves ~2h/month
    hooksCount * 1.5 + // Each hook saves ~1.5h/month
    docsCount * 0.5; // Each doc saves ~0.5h/month

  const estimatedHours = Math.round(baseSavingsPerMonth);

  const keyBenefits = [
    `${skillsCount} reusable AI workflows — stop rewriting prompts`,
    `${hooksCount} automated quality gates — enforce standards automatically`,
    `${docsCount} architecture documents — the "why" is always accessible`,
    `1 project brain (CLAUDE.md) — consistent AI context every session`,
    `Estimated ${estimatedHours}h/month saved per developer`,
    `New developers productive in days, not weeks`,
    `AI output quality improves as CLAUDE.md matures`,
  ];

  return {
    totalFiles,
    skillsCount,
    hooksCount,
    docsCount,
    estimatedTimeSavings: `~${estimatedHours}h/month per developer`,
    keyBenefits,
  };
}

// ── Utility: generate a shell install script ────────────────────────────────

export function generateInstallScript(pkg: ClaudePackage): string {
  const fileList = pkg.files
    .map((f) => {
      const dir = f.path.split('/').slice(0, -1).join('/');
      const escapedContent = f.content
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "'\\''");
      return `mkdir -p "${dir}" && cat > "${f.path}" << 'SKILL_CREATOR_EOF'\n${f.content}\nSKILL_CREATOR_EOF`;
    })
    .join('\n\n');

  return `#!/bin/bash
# Generated by Skill Creator
# Installs .claude/ structure for optimal Claude Code usage
# Usage: bash install-claude.sh

set -e

echo "🤖 Setting up .claude/ structure..."
echo "   This will create ${pkg.summary.totalFiles} files in your project"
echo ""

${fileList}

echo ""
echo "✅ .claude/ structure installed successfully!"
echo ""
echo "📁 Created:"
echo "   .claude/CLAUDE.md          → Project brain"
echo "   .claude/skills/ (${pkg.summary.skillsCount} files)  → AI workflows"
echo "   .claude/hooks/  (${pkg.summary.hooksCount} files)  → Quality gates"
echo "   .claude/docs/   (${pkg.summary.docsCount} files)  → Architecture docs"
echo ""
echo "🚀 Next steps:"
echo "   1. Review and customize .claude/CLAUDE.md"
echo "   2. Run: claude /skills to verify skills loaded"
echo "   3. Commit the .claude/ directory to version control"
echo ""
echo "💡 Tip: git add .claude/ && git commit -m 'chore: add Claude Code structure'"
`;
}

// ── Utility: generate a structured tree view ───────────────────────────────

export function generateTreeView(pkg: ClaudePackage): string {
  const { skillsCount, hooksCount, docsCount } = pkg.summary;

  const skillLines = pkg.structure.skills
    .map((s) => `│   ├── ${s.filename.padEnd(35)} # ${s.description.slice(0, 50)}`)
    .join('\n');

  const hookLines = pkg.structure.hooks
    .map((h) => `│   ├── ${h.filename.padEnd(35)} # ${h.description.slice(0, 50)}`)
    .join('\n');

  const docLines = pkg.structure.docs
    .map((d) => `│   ├── ${d.filename.padEnd(35)} # ${d.description.slice(0, 50)}`)
    .join('\n');

  return `.claude/
├── CLAUDE.md                               # Project brain — context, rules, conventions
│
├── skills/ (${skillsCount} files)
${skillLines}
│
├── hooks/ (${hooksCount} files)
${hookLines}
│
└── docs/ (${docsCount} files)
${docLines}

Total: ${pkg.summary.totalFiles} files
Estimated value: ${pkg.summary.estimatedTimeSavings}
`;
}
